### ISSUE TITLE
How to Inject this service into the Route

### ISSUE THREAD

**Issue by JacobSamro** [dockyard/ember-cart#36]
Will you please explain how to inject this service into a route.

**Comment by bcardarella** [comment]
I think you have found a bug. The service is currently injected to Controllers and Components as `cart:main` however that means if you try and inject the service in the way services want to be injected in Ember:

```js
cart: inject()
```

it will not work as expected as it will create difference instance.

I think the way to do this is to remove the instance initializer and just rely on service injection. If you want to PR this change let me know. Else I can probably do it later this week.

**Comment by JacobSamro** [comment]
Great it worked ! Thanks :dancing_men:
